### ISSUE TITLE
Check your Learning solutions for mentors

### ISSUE THREAD

**Issue by elcorto** [deeplearning540/deeplearning540.github.io#27]
It would be good to have solutions to all questions. Most are obvious, but not all.

**Comment by psteinb** [comment]
Please make a suggestion, where to put these solutions without learners stumbling on them.

**Comment by psteinb** [comment]
Happy to share the solutions, and happy to receive PRs on this. I am simply not sure where to put it.

**Comment by elcorto** [comment]
The carpentries material is in markdown and they use something like [this](https://github.com/swcarpentry/python-novice-inflammation/blame/gh-pages/_episodes/01-intro.md#L254). I'm super bad at web stuff but [I found a solution for rst](https://stackoverflow.com/a/60394068) that even I understand, bit verbose, but still:

```rst
Now below, check something hidden.

.. raw:: html

   <details>

   <summary>This is a title, instead of just "Details"</summary>

.. code-block:: python

   def foo():
       return bar

.. raw:: html

   </details>

Normal text here.
```
